apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlays/local
patches:
  - target:
      kind: ConfigMap
      name: careflow-api-config
    patch: |-
      - op: replace
        path: /data/APP_VERSION
        value: 0.2.0-readiness-failure
      - op: add
        path: /data/FORCE_READINESS_FAILURE
        value: "true"
