apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: careflow-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: careflow-platform
  source:
    repoURL: https://github.com/REPLACE_ME/enterprise-multiregion-cloud-platform.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: careflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
