apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - external-secrets-application.yaml
  - load-balancer-controller-application.yaml
  - metrics-server-application.yaml
  - kyverno-application.yaml
  - kyverno-policies-application.yaml
  - observability-application.yaml
  - careflow-application.yaml
