apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: careflow-kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-29"
spec:
  project: careflow-platform
  source:
    repoURL: https://github.com/REPLACE_ME/enterprise-multiregion-cloud-platform.git
    targetRevision: main
    path: platform/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
