apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  project: careflow-platform
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 3.5.0
    helm:
      valuesObject:
        clusterName: REPLACE_ME_EKS_CLUSTER_NAME
        region: us-east-1
        vpcId: REPLACE_ME_VPC_ID
        replicaCount: 2
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/REPLACE_ME-aws-load-balancer-controller
        enableShield: false
        enableWaf: false
        enableWafv2: false
        resources:
          requests:
            cpu: 50m
            memory: 96Mi
          limits:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
