apiVersion: v1
kind: Namespace
metadata:
  name: careflow
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    networking.careflow.io/ingress: "true"
